name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: "🚀 Features"
    labels: ["feature", "enhancement", "feat"]
  - title: "🐛 Fixes"
    labels: ["bug", "fix"]
  - title: "📚 Docs"
    labels: ["docs"]
  - title: "🧹 Refactors"
    labels: ["refactor"]
  - title: "🧰 Maintenance"
    labels: ["chore", "dependencies"]
  - title: "🧪 CI"
    labels: ["ci"]

change-template: "- $TITLE (#$NUMBER) by @$AUTHOR"
no-changes-template: "- No user-facing changes."

version-resolver:
  major:
    labels: ["major"]
  minor:
    labels: ["minor", "feature", "enhancement", "feat"]
  patch:
    labels: ["patch", "bug", "fix", "docs", "refactor", "chore", "ci", "dependencies"]
  default: patch

autolabeler:
  - label: "feat"
    title:
      - "/^feat(\\(.+\\))?:/i"
  - label: "fix"
    title:
      - "/^fix(\\(.+\\))?:/i"
  - label: "docs"
    title:
      - "/^docs(\\(.+\\))?:/i"
  - label: "refactor"
    title:
      - "/^refactor(\\(.+\\))?:/i"
  - label: "chore"
    title:
      - "/^chore(\\(.+\\))?:/i"
  - label: "ci"
    title:
      - "/^ci(\\(.+\\))?:/i"
      - "/^chore\\(ci\\):/i"

template: |
  ## What's Changed
  $CHANGES

  ## Contributors
  $CONTRIBUTORS
